name: Publish yarn-core package
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  publish:
    runs-on: [ubuntu-latest]
    steps:
      - name: Publish yarn-core package
        uses: actions/upload-artifact@v1.0.0
        with:
          name: yarn-core
          path: .
